"""initial schema

Revision ID: 3a504da8457d
Revises: 
Create Date: 2026-07-24 09:20:38.527235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a504da8457d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_table('norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norms_reference'), 'norms', ['reference'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('article_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('has_battery', sa.Boolean(), nullable=False),
    sa.Column('has_manual', sa.Boolean(), nullable=False),
    sa.Column('specification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_article_number'), 'products', ['article_number'], unique=False)
    op.create_index(op.f('ix_products_customer_id'), 'products', ['customer_id'], unique=False)
    op.create_table('test_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['test_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_categories_customer_id'), 'test_categories', ['customer_id'], unique=False)
    op.create_index(op.f('ix_test_categories_parent_id'), 'test_categories', ['parent_id'], unique=False)
    op.create_table('test_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_programs_customer_id'), 'test_programs', ['customer_id'], unique=False)
    op.create_table('test_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('norm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicability_condition', sa.String(length=100), nullable=True),
    sa.Column('is_default_selected', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['test_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['norm_id'], ['norms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_catalog_items_category_id'), 'test_catalog_items', ['category_id'], unique=False)
    op.create_table('test_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_orders_customer_id'), 'test_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_test_orders_product_id'), 'test_orders', ['product_id'], unique=False)
    op.create_table('test_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('test_order_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['test_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_order_id'], ['test_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plans_customer_id'), 'test_plans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_test_plans_product_id'), 'test_plans', ['product_id'], unique=False)
    op.create_table('test_program_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['test_catalog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['test_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_program_items_catalog_item_id'), 'test_program_items', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_test_program_items_program_id'), 'test_program_items', ['program_id'], unique=False)
    op.create_table('test_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('norm_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['test_catalog_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plan_items_test_plan_id'), 'test_plan_items', ['test_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_plan_items_test_plan_id'), table_name='test_plan_items')
    op.drop_table('test_plan_items')
    op.drop_index(op.f('ix_test_program_items_program_id'), table_name='test_program_items')
    op.drop_index(op.f('ix_test_program_items_catalog_item_id'), table_name='test_program_items')
    op.drop_table('test_program_items')
    op.drop_index(op.f('ix_test_plans_product_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_customer_id'), table_name='test_plans')
    op.drop_table('test_plans')
    op.drop_index(op.f('ix_test_orders_product_id'), table_name='test_orders')
    op.drop_index(op.f('ix_test_orders_customer_id'), table_name='test_orders')
    op.drop_table('test_orders')
    op.drop_index(op.f('ix_test_catalog_items_category_id'), table_name='test_catalog_items')
    op.drop_table('test_catalog_items')
    op.drop_index(op.f('ix_test_programs_customer_id'), table_name='test_programs')
    op.drop_table('test_programs')
    op.drop_index(op.f('ix_test_categories_parent_id'), table_name='test_categories')
    op.drop_index(op.f('ix_test_categories_customer_id'), table_name='test_categories')
    op.drop_table('test_categories')
    op.drop_index(op.f('ix_products_customer_id'), table_name='products')
    op.drop_index(op.f('ix_products_article_number'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_norms_reference'), table_name='norms')
    op.drop_table('norms')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
