"""add master data tables and testplanitem cost fields

Revision ID: 4fcd177fa50f
Revises: 3a504da8457d
Create Date: 2026-07-24 09:50:06.324221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcd177fa50f'
down_revision: Union[str, None] = '3a504da8457d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lidl_warengruppe_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lidl_bereich', sa.String(length=255), nullable=False),
    sa.Column('lidl_warengruppe', sa.String(length=255), nullable=True),
    sa.Column('warengruppe_code', sa.Integer(), nullable=True),
    sa.Column('produkt', sa.String(length=255), nullable=True),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.Column('trivial', sa.Boolean(), nullable=False),
    sa.Column('norm_ek_ppm', sa.String(length=255), nullable=True),
    sa.Column('anzahl_muster', sa.String(length=100), nullable=True),
    sa.Column('kez_anforderung', sa.Boolean(), nullable=False),
    sa.Column('kosten_vp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ffu_code', sa.Text(), nullable=True),
    sa.Column('kosten_ffu', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stiwa_referenz', sa.Text(), nullable=True),
    sa.Column('kosten_stiwa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bewertung_uv', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lidl_warengruppe_rules_lidl_bereich'), 'lidl_warengruppe_rules', ['lidl_bereich'], unique=False)
    op.create_index(op.f('ix_lidl_warengruppe_rules_lidl_warengruppe'), 'lidl_warengruppe_rules', ['lidl_warengruppe'], unique=False)
    op.create_index(op.f('ix_lidl_warengruppe_rules_warengruppe_code'), 'lidl_warengruppe_rules', ['warengruppe_code'], unique=False)
    op.create_table('norm_lookup_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategorie', sa.String(length=255), nullable=False),
    sa.Column('produktart', sa.String(length=255), nullable=False),
    sa.Column('zielgruppe', sa.String(length=255), nullable=True),
    sa.Column('einsatzort', sa.String(length=255), nullable=True),
    sa.Column('bereich', sa.String(length=255), nullable=True),
    sa.Column('produkt', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=500), nullable=False),
    sa.Column('lidl_warengruppe', sa.String(length=255), nullable=True),
    sa.Column('normen', sa.String(length=500), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('verweise', sa.Text(), nullable=True),
    sa.Column('preis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('zeit_labor_min', sa.Integer(), nullable=True),
    sa.Column('kosten_labor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norm_lookup_rules_code'), 'norm_lookup_rules', ['code'], unique=True)
    op.create_index(op.f('ix_norm_lookup_rules_kategorie'), 'norm_lookup_rules', ['kategorie'], unique=False)
    op.create_index(op.f('ix_norm_lookup_rules_produkt'), 'norm_lookup_rules', ['produkt'], unique=False)
    op.create_index(op.f('ix_norm_lookup_rules_produktart'), 'norm_lookup_rules', ['produktart'], unique=False)
    op.create_table('norm_special_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategorie', sa.String(length=255), nullable=True),
    sa.Column('produktart', sa.String(length=255), nullable=True),
    sa.Column('zielgruppe', sa.String(length=255), nullable=True),
    sa.Column('einsatzort', sa.String(length=255), nullable=True),
    sa.Column('eigenschaft', sa.String(length=255), nullable=False),
    sa.Column('zusatzkosten', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kommentar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norm_special_items_eigenschaft'), 'norm_special_items', ['eigenschaft'], unique=False)
    op.create_index(op.f('ix_norm_special_items_kategorie'), 'norm_special_items', ['kategorie'], unique=False)
    op.create_index(op.f('ix_norm_special_items_produktart'), 'norm_special_items', ['produktart'], unique=False)
    op.create_table('product_spec_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=False),
    sa.Column('produkt', sa.String(length=255), nullable=True),
    sa.Column('mak', sa.String(length=100), nullable=True),
    sa.Column('norm', sa.String(length=255), nullable=True),
    sa.Column('material_code', sa.String(length=255), nullable=True),
    sa.Column('laufzeit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('formel_laufzeit', sa.String(length=500), nullable=True),
    sa.Column('kosten', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bewertung', sa.Text(), nullable=True),
    sa.Column('anzahl_proben', sa.String(length=255), nullable=True),
    sa.Column('formel_bewertung', sa.String(length=500), nullable=True),
    sa.Column('kosten_bewertung', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('formel_staffelung', sa.String(length=500), nullable=True),
    sa.Column('kosten_staffelung', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gesamtkosten', sa.String(length=255), nullable=True),
    sa.Column('vk_preis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pruefstelle', sa.String(length=255), nullable=True),
    sa.Column('kontakt', sa.String(length=255), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('materialverkaufstext', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_spec_requirements_parameter'), 'product_spec_requirements', ['parameter'], unique=False)
    op.create_index(op.f('ix_product_spec_requirements_produkt'), 'product_spec_requirements', ['produkt'], unique=False)
    op.add_column('test_plan_items', sa.Column('lab_minutes', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('test_plan_items', sa.Column('lab_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('test_plan_items', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_plan_items', 'sale_price')
    op.drop_column('test_plan_items', 'lab_cost')
    op.drop_column('test_plan_items', 'lab_minutes')
    op.drop_index(op.f('ix_product_spec_requirements_produkt'), table_name='product_spec_requirements')
    op.drop_index(op.f('ix_product_spec_requirements_parameter'), table_name='product_spec_requirements')
    op.drop_table('product_spec_requirements')
    op.drop_index(op.f('ix_norm_special_items_produktart'), table_name='norm_special_items')
    op.drop_index(op.f('ix_norm_special_items_kategorie'), table_name='norm_special_items')
    op.drop_index(op.f('ix_norm_special_items_eigenschaft'), table_name='norm_special_items')
    op.drop_table('norm_special_items')
    op.drop_index(op.f('ix_norm_lookup_rules_produktart'), table_name='norm_lookup_rules')
    op.drop_index(op.f('ix_norm_lookup_rules_produkt'), table_name='norm_lookup_rules')
    op.drop_index(op.f('ix_norm_lookup_rules_kategorie'), table_name='norm_lookup_rules')
    op.drop_index(op.f('ix_norm_lookup_rules_code'), table_name='norm_lookup_rules')
    op.drop_table('norm_lookup_rules')
    op.drop_index(op.f('ix_lidl_warengruppe_rules_warengruppe_code'), table_name='lidl_warengruppe_rules')
    op.drop_index(op.f('ix_lidl_warengruppe_rules_lidl_warengruppe'), table_name='lidl_warengruppe_rules')
    op.drop_index(op.f('ix_lidl_warengruppe_rules_lidl_bereich'), table_name='lidl_warengruppe_rules')
    op.drop_table('lidl_warengruppe_rules')
    # ### end Alembic commands ###
