"""add product classification fields for norm lookup

Revision ID: 9b7aa9b2d50a
Revises: ddf5f11621fb
Create Date: 2026-07-24 11:27:35.758753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7aa9b2d50a'
down_revision: Union[str, None] = 'ddf5f11621fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('kategorie', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('produktart', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('zielgruppe', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('einsatzort', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('bereich', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('produkt_typ', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'produkt_typ')
    op.drop_column('products', 'bereich')
    op.drop_column('products', 'einsatzort')
    op.drop_column('products', 'zielgruppe')
    op.drop_column('products', 'produktart')
    op.drop_column('products', 'kategorie')
    # ### end Alembic commands ###
