"""widen lidl_warengruppe_rules.norm_ek_ppm to text

Revision ID: ddf5f11621fb
Revises: 4fcd177fa50f
Create Date: 2026-07-24 09:51:42.027135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf5f11621fb'
down_revision: Union[str, None] = '4fcd177fa50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lidl_warengruppe_rules', 'norm_ek_ppm',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lidl_warengruppe_rules', 'norm_ek_ppm',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
